version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: superheroes-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: superheroes
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - superheroes-network

networks:
  superheroes-network: